import { randomInt } from "crypto";
import { writeFileSync } from "fs";
import path from "path";

async function main() {
  const argv = process.argv.slice(2);
  const workspaceId = argv[0] || "ws_test";
  const count = Number(argv[1] ?? 500);

  const providers = ["OpenAI", "Gemini", "Anthropic"];
  const models = ["gpt-4o", "gpt-4o-mini", "gemini-2.5-flash", "claude-sonnet"];
  const routes = ["/api/chat", "/api/summarize", "/api/translate", "/api/embeddings", "/api/qa"];

  let rows: string[] = [];
  const now = Date.now();

  let openaiSpend = 0;
  let totalSpend = 0;

  for (let i = 0; i < count; i++) {
    const ts = now - randomInt(0, 1000 * 60 * 60 * 24 * 7);
    const provider = Math.random() < 0.8 ? "OpenAI" : providers[randomInt(1, providers.length)];
    let model: string;
    if (provider === "OpenAI") model = Math.random() < 0.6 ? "gpt-4o" : "gpt-4o-mini";
    else if (provider === "Gemini") model = "gemini-2.5-flash";
    else model = "claude-sonnet";

    const route = routes[randomInt(0, routes.length)];
    const input_tokens = randomInt(5, 800);
    const output_tokens = randomInt(5, 2000);
    const total_tokens = input_tokens + output_tokens;

    let cost_usd = 0.00001 * total_tokens;
    if (provider === "OpenAI") cost_usd = total_tokens * 0.00006;
    if (provider === "Gemini") cost_usd = total_tokens * 0.00001;
    if (provider === "Anthropic") cost_usd = total_tokens * 0.00003;

    let latency_ms = 100 + randomInt(0, 500);
    if (route === "/api/qa" && Math.random() < 0.2) latency_ms += 2000;

    const error = Math.random() < 0.02 ? "HTTP_500_INTERNAL" : null;

    const metadata = JSON.stringify({ note: "seeded" }).replace(/'/g, "''");

    const errorSql = error ? ("'" + error + "'") : 'NULL';

    rows.push(
      "('" + workspaceId + "', " + ts + ", '" + route + "', '" + model + "', '" + provider + "', " + input_tokens + ", " + output_tokens + ", " + total_tokens + ", " + cost_usd.toFixed(8) + ", " + latency_ms + ", " + errorSql + ", '" + metadata + "')"
    );

    totalSpend += cost_usd;
    if (provider === "OpenAI") openaiSpend += cost_usd;
  }

  const openaiPct = (openaiSpend / Math.max(1e-9, totalSpend)) * 100;
  if (openaiPct < 75) {
    for (let i = 0; i < Math.floor((75 - openaiPct) / 2) && i < rows.length; i++) {
      rows[i] = rows[i].replace(/'(Gemini|Anthropic)'/, "'OpenAI'");
    }
  }

  const sqlLines = [];
  sqlLines.push('-- Temporary seed SQL generated by seedAiInsightsData.ts');
  sqlLines.push('BEGIN;');
  sqlLines.push('INSERT INTO requests (workspace_id, timestamp, route, model, provider, input_tokens, output_tokens, total_tokens, cost_usd, latency_ms, error, metadata) VALUES');
  sqlLines.push(rows.join(',\n') + ';');
  sqlLines.push('COMMIT;');

  const file = sqlLines.join('\n');
  const outPath = path.resolve(process.cwd(), 'backend', 'scripts', 'seed-' + workspaceId + '-requests.sql');
  writeFileSync(outPath, file, 'utf-8');

  console.log('Wrote ' + rows.length + ' rows to ' + outPath);
  console.log('Estimated total spend: $' + totalSpend.toFixed(4) + ' (OpenAI share ~' + openaiPct.toFixed(1) + '%)');
  console.log('Run the SQL with psql against your PostgreSQL database to insert the rows.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
