export interface EmailMetric {
  label: string;
  value: string;
}

export interface EmailTable {
  title: string;
  columns: string[];
  rows: Array<Array<string | number>>;
}

export interface EmailRecommendation {
  title: string;
  detail: string;
}

export interface TokenWatcherEmailTemplateInput {
  eyebrow: string;
  title: string;
  intro: string;
  metadata: EmailMetric[];
  metrics: EmailMetric[];
  tables?: EmailTable[];
  recommendations?: EmailRecommendation[];
}

export function renderTokenWatcherEmail(input: TokenWatcherEmailTemplateInput): string {
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(input.title)}</title>
  </head>
  <body style="margin:0;background:#f6f5f2;color:#191919;font-family:Inter,Arial,sans-serif;">
    <main style="max-width:720px;margin:0 auto;padding:32px 20px;">
      <div style="border-bottom:1px solid #b7b3aa;padding-bottom:14px;margin-bottom:28px;">
        <div style="font-family:Georgia,serif;font-size:24px;line-height:1;">TokenWatcher</div>
        <div style="margin-top:8px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#62605b;">${escapeHtml(input.eyebrow)}</div>
      </div>

      <h1 style="font-family:Georgia,serif;font-size:36px;line-height:1.05;font-weight:400;margin:0 0 16px;">${escapeHtml(input.title)}</h1>
      <p style="font-size:15px;line-height:1.7;margin:0 0 28px;color:#44413c;">${escapeHtml(input.intro)}</p>

      ${renderMetrics("Metadata", input.metadata)}
      ${renderMetrics("Summary", input.metrics)}
      ${(input.tables ?? []).map(renderTable).join("")}
      ${input.recommendations?.length ? renderRecommendations(input.recommendations) : ""}

      <div style="border-top:1px solid #b7b3aa;margin-top:32px;padding-top:14px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#62605b;">
        Generated by TokenWatcher Governance. Review workspace settings to change notification delivery.
      </div>
    </main>
  </body>
</html>`;
}

function renderMetrics(title: string, metrics: EmailMetric[]): string {
  if (metrics.length === 0) return "";
  return `
    <section style="border-top:1px solid #b7b3aa;margin-top:22px;padding-top:12px;">
      <div style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#62605b;margin-bottom:8px;">${escapeHtml(title)}</div>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <tbody>
          ${metrics.map((metric) => `
            <tr>
              <td style="border-bottom:1px solid #d9d5cc;padding:8px 8px 8px 0;color:#62605b;">${escapeHtml(metric.label)}</td>
              <td style="border-bottom:1px solid #d9d5cc;padding:8px 0;text-align:right;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;">${escapeHtml(metric.value)}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
    </section>`;
}

function renderTable(table: EmailTable): string {
  return `
    <section style="border-top:1px solid #b7b3aa;margin-top:24px;padding-top:12px;">
      <div style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#62605b;margin-bottom:8px;">${escapeHtml(table.title)}</div>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <thead>
          <tr>${table.columns.map((column) => `<th style="border-bottom:1px solid #b7b3aa;padding:8px;text-align:left;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#62605b;">${escapeHtml(column)}</th>`).join("")}</tr>
        </thead>
        <tbody>
          ${table.rows.map((row) => `<tr>${row.map((cell) => `<td style="border-bottom:1px solid #d9d5cc;padding:8px;">${escapeHtml(String(cell))}</td>`).join("")}</tr>`).join("")}
        </tbody>
      </table>
    </section>`;
}

function renderRecommendations(items: EmailRecommendation[]): string {
  return `
    <section style="border-top:1px solid #b7b3aa;margin-top:24px;padding-top:12px;">
      <div style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#62605b;margin-bottom:8px;">Recommendations</div>
      ${items.map((item) => `
        <div style="border-bottom:1px solid #d9d5cc;padding:10px 0;">
          <div style="font-family:Georgia,serif;font-size:18px;">${escapeHtml(item.title)}</div>
          <div style="font-size:13px;line-height:1.6;color:#44413c;margin-top:4px;">${escapeHtml(item.detail)}</div>
        </div>
      `).join("")}
    </section>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
